# Generated by Django 5.0.1 on 2026-02-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realisations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realisation',
            options={'ordering': ['ordre', '-created_at'], 'verbose_name': 'Réalisation', 'verbose_name_plural': 'Réalisations'},
        ),
        migrations.AddField(
            model_name='realisation',
            name='client',
            field=models.CharField(blank=True, help_text="Nom de l'entreprise cliente", max_length=200, null=True, verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='realisation',
            name='ordre',
            field=models.PositiveIntegerField(default=0, help_text="Priorité d'affichage (0 = le plus prioritaire)", verbose_name="Ordre d'affichage"),
        ),
        migrations.AddField(
            model_name='realisation',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé')], default='termine', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='realisation',
            name='technologies',
            field=models.CharField(blank=True, help_text='Ex: React, Django, PostgreSQL', max_length=500, null=True, verbose_name='Technologies utilisées'),
        ),
    ]
