# Generated by Django 5.0.1 on 2026-02-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realisations', '0002_alter_realisation_options_realisation_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realisation',
            name='categorie',
            field=models.CharField(choices=[('developpement', 'Développement Web'), ('formation', 'Formation & Atelier'), ('conseil', 'Conseil & Stratégie')], default='developpement', max_length=50, verbose_name='Catégorie'),
        ),
    ]
