# Generated by Django 5.0.1 on 2026-03-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realisations', '0003_realisation_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realisation',
            name='categorie',
            field=models.CharField(choices=[('developpement', 'Développement Web'), ('formation', 'Formation & Atelier'), ('conseil', 'Conseil & Stratégie'), ('automatisation', 'IA & Automatisation')], default='developpement', max_length=50, verbose_name='Catégorie'),
        ),
    ]
