# Generated by Django 5.0.1 on 2026-02-15 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['ordre', '-created_at'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AddField(
            model_name='service',
            name='description_courte',
            field=models.CharField(default=1, help_text='Résumé en une phrase', max_length=255, verbose_name='Description courte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='duree_estimee',
            field=models.CharField(blank=True, help_text="Ex: '2-4 semaines'", max_length=100, verbose_name='Durée estimée'),
        ),
        migrations.AddField(
            model_name='service',
            name='est_actif',
            field=models.BooleanField(default=True, verbose_name='Service actif'),
        ),
        migrations.AddField(
            model_name='service',
            name='ordre',
            field=models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
        ),
        migrations.AddField(
            model_name='service',
            name='points_forts',
            field=models.JSONField(blank=True, default=list, help_text="Liste des avantages (ex: ['Point 1', 'Point 2'])", verbose_name='Points forts'),
        ),
        migrations.AddField(
            model_name='service',
            name='prix_a_partir_de',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix à partir de (FCFA)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Description détaillée'),
        ),
        migrations.AlterField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
