# Generated by Django 5.0.1 on 2026-02-15 11:30

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='description',
        ),
        migrations.AddField(
            model_name='formation',
            name='description_complete',
            field=models.TextField(default=1, verbose_name='Description complète'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formation',
            name='description_courte',
            field=models.TextField(default=1, help_text='Résumé pour la liste', max_length=500, verbose_name='Description courte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formation',
            name='duree',
            field=models.CharField(blank=True, help_text='Ex: 3 mois, 40 heures', max_length=100, verbose_name='Durée'),
        ),
        migrations.AddField(
            model_name='formation',
            name='niveau',
            field=models.CharField(blank=True, help_text='Ex: Débutant, Intermédiaire', max_length=50, verbose_name='Niveau'),
        ),
        migrations.AddField(
            model_name='formation',
            name='sous_titre',
            field=models.CharField(blank=True, max_length=300, verbose_name='Sous-titre'),
        ),
        migrations.AddField(
            model_name='formation',
            name='syllabus',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix (FCFA)'),
        ),
    ]
